#!/bin/bash
# =======================================================================================
# Script Name : daily_backup_summary_10232025.sh
# Purpose     : Generate Daily Backup Summary and Email HTML Report
# Author      : Yvette Halili
# =======================================================================================

set -euo pipefail

# === CONFIGURATION ===
DB_USER="trtel.backup"
DB_PASS="Telus2017#"
DB_NAME="ti_db_inventory"
REPORT_DATE=$(date -d "yesterday" '+%Y-%m-%d')
DIR="backup"
mkdir -p "${DIR}"
emailFile="${DIR}/daily_backup_report.html"

# === FETCH BACKUP SIZE PER DB ENGINE (in GB) ===
engine_storage=$(mysql -u"${DB_USER}" -p"${DB_PASS}" -D"${DB_NAME}" -N -e "
SELECT DB_engine,
       ROUND(SUM(CASE size_name
           WHEN 'B'  THEN size/1024/1024/1024
           WHEN 'KB' THEN size/1024/1024
           WHEN 'MB' THEN size/1024
           WHEN 'GB' THEN size
           ELSE 0 END), 2) AS TotalGB
FROM daily_backup_report
WHERE backup_date = '${REPORT_DATE}'
GROUP BY DB_engine;
")

# === FETCH TOP 5 LARGEST BACKUPS (in MB) ===
top_backups=$(mysql -u"${DB_USER}" -p"${DB_PASS}" -D"${DB_NAME}" -N -e "
SELECT Server,
       DB_engine,
       ROUND(SUM(CASE size_name
           WHEN 'B'  THEN size / 1024 / 1024
           WHEN 'KB' THEN size / 1024
           WHEN 'MB' THEN size
           WHEN 'GB' THEN size * 1024
           ELSE 0 END), 2) AS TotalMB
FROM daily_backup_report
WHERE backup_date = '${REPORT_DATE}'
GROUP BY Server, DB_engine
ORDER BY TotalMB DESC
LIMIT 5;
")

# === PREPARE ARRAYS FOR CHART DATA ===
LABELS=()
DATA=()

while read -r engine total; do
    [[ -z "$engine" ]] && continue
    LABELS+=("$engine")
    DATA+=("$total")
done <<< "$engine_storage"

# === CONVERT ARRAYS TO JSON (safe parsing) ===
LABELS_JSON=$(printf '%s\n' "${LABELS[@]}" | jq -R -s -c 'split("\n") | map(select(length>0))')
DATA_JSON=$(printf '%s\n' "${DATA[@]}" | jq -R -s -c 'split("\n") | map(select(length>0)) | map(tonumber)')

# === CREATE HTML EMAIL REPORT ===
cat > "${emailFile}" <<EOF
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Daily Backup Summary - ${REPORT_DATE}</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
    h2, h3 { color: #2c3e50; }
    table { border-collapse: collapse; width: 60%; margin-top: 10px; }
    th, td { border: 1px solid #999; padding: 8px; text-align: left; }
    th { background-color: #f2f2f2; }
    canvas { margin-top: 15px; }
  </style>
</head>
<body>
  <h2>📊 Daily Backup Summary - ${REPORT_DATE}</h2>

  <h3>Backup Size (GB) per DB Engine</h3>
  <canvas id="backupChart" width="400" height="200"></canvas>

  <script>
    const ctx = document.getElementById('backupChart');
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ${LABELS_JSON},
        datasets: [{
          label: 'Total Backup Size (GB)',
          data: ${DATA_JSON},
          backgroundColor: ['#36A2EB', '#FF6384', '#FFCE56', '#4BC0C0', '#9966FF'],
          borderWidth: 1
        }]
      },
      options: {
        responsive: true,
        scales: {
          y: { beginAtZero: true, title: { display: true, text: 'Size (GB)' } }
        },
        plugins: {
          legend: { display: false },
          title: { display: true, text: 'Backup Size per DB Engine (GB)' }
        }
      }
    });
  </script>

  <h3>Top 5 Largest Backups (MB)</h3>
  <table>
    <tr><th>Server</th><th>DB Engine</th><th>Total Size (MB)</th></tr>
EOF

# === APPEND TABLE ROWS ===
while read -r server engine total; do
    [[ -z "$server" ]] && continue
    echo "<tr><td>${server}</td><td>${engine}</td><td align='right'>${total}</td></tr>" >> "${emailFile}"
done <<< "$top_backups"

# === CLOSE HTML ===
cat >> "${emailFile}" <<EOF
  </table>
  <br><p>Report automatically generated by <b>daily_backup_summary_10232025.sh</b>.</p>
</body>
</html>
EOF

# === SEND EMAIL ===
mail -a "Content-Type: text/html" -s "Daily Backup Summary - ${REPORT_DATE}" yvette.halili@telusinternational.com < "${emailFile}"

echo " Email sent to yvette.halili@telusinternational.com"
