#!/bin/bash

# === CONFIGURATION ===
DB_USER="trtel.backup"
DB_PASS="Telus2017#"
DB_NAME="ti_db_inventory"
REPORT_DATE=$(date -d "yesterday" '+%Y-%m-%d')
DIR="backup"
mkdir -p "${DIR}"
emailFile="${DIR}/daily_backup_report.html"
LOG_FILE="${DIR}/debug.log"
: > "${LOG_FILE}"

# === EXECUTIVE METRICS ===
read total_count error_count <<< $(mysql -u"${DB_USER}" -p"${DB_PASS}" -D"${DB_NAME}" -N -e "
SELECT COUNT(*), SUM(IF(size = 0.00 AND size_name = 'B', 1, 0))
FROM daily_backup_report
WHERE backup_date = '${REPORT_DATE}';
")

success_count=$((total_count - error_count))
success_rate=$(awk "BEGIN {printf \"%.1f\", (${success_count}/${total_count})*100}")
total_storage=$(mysql -u"${DB_USER}" -p"${DB_PASS}" -D"${DB_NAME}" -N -e "
SELECT ROUND(SUM(CASE size_name
    WHEN 'B' THEN size/1024/1024/1024
    WHEN 'KB' THEN size/1024/1024
    WHEN 'MB' THEN size/1024
    WHEN 'GB' THEN size
    ELSE 0 END), 1)
FROM daily_backup_report
WHERE backup_date = '${REPORT_DATE}';
")

# === CHART URLs ===
DONUT_CHART_URL="https://quickchart.io/chart?c=$(jq -sRr @uri <<EOF
{
  "type": "doughnut",
  "data": {
    "labels": ["Success", "Failure"],
    "datasets": [{
      "data": [${success_count}, ${error_count}],
      "backgroundColor": ["#4B286D", "#00B7C3"]
    }]
  },
  "options": {
    "plugins": {
      "title": {
        "display": true,
        "text": "Backup Status Overview"
      },
      "legend": {
        "position": "bottom"
      }
    }
  }
}
EOF
)"

read -r mysql_size pgsql_size mssql_size <<< $(mysql -u"${DB_USER}" -p"${DB_PASS}" -D"${DB_NAME}" -N -e "
SELECT
  ROUND(SUM(CASE WHEN DB_engine='MYSQL' THEN CASE size_name WHEN 'GB' THEN size ELSE 0 END ELSE 0 END), 1),
  ROUND(SUM(CASE WHEN DB_engine='PGSQL' THEN CASE size_name WHEN 'GB' THEN size ELSE 0 END ELSE 0 END), 1),
  ROUND(SUM(CASE WHEN DB_engine='MSSQL' THEN CASE size_name WHEN 'GB' THEN size ELSE 0 END ELSE 0 END), 1)
FROM daily_backup_report
WHERE backup_date = '${REPORT_DATE}';
")

STACKED_CHART_URL="https://quickchart.io/chart?c=$(jq -sRr @uri <<EOF
{
  "type": "bar",
  "data": {
    "labels": ["MySQL", "PostgreSQL", "MSSQL"],
    "datasets": [{
      "label": "GB Size",
      "data": [${mysql_size}, ${pgsql_size}, ${mssql_size}],
      "backgroundColor": ["#00B7C3", "#4B286D", "#F4F4F4"]
    }]
  },
  "options": {
    "plugins": {
      "title": {
        "display": true,
        "text": "Daily Storage Utilization per Type"
      },
      "legend": {
        "display": false
      }
    },
    "scales": {
      "x": { "stacked": true },
      "y": { "stacked": true }
    }
  }
}
EOF
)"

# === TOP 5 BACKUPS TABLE ===
top_backups=$(mysql -u"${DB_USER}" -p"${DB_PASS}" -D"${DB_NAME}" -e "
SELECT Server, DB_engine, CONCAT(size, ' ', size_name) AS Size
FROM daily_backup_report
WHERE backup_date = '${REPORT_DATE}'
ORDER BY size DESC
LIMIT 5;
")

# === EMAIL HTML ===
{
echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><style>
body { font-family: 'Helvetica Neue', Arial, sans-serif; background-color: #f4f4f4; color: #333; padding: 20px; }
.container { max-width: 800px; margin: auto; background-color: #fff; padding: 20px; border-radius: 10px; }
h1, h2 { color: #4B286D; text-align: center; }
table { width: 100%; border-collapse: collapse; margin-top: 20px; }
th, td { padding: 10px; border: 1px solid #ddd; text-align: left; }
tr:nth-child(even) { background-color: #f9f9f9; }
</style></head><body><div class='container'>"

echo "<h1>Daily Backup Report - ${REPORT_DATE}</h1>"
echo "<div style='padding: 15px; background-color: #f7f3fb; border-left: 5px solid #4B286D; margin-bottom: 20px;'>"
echo "<p><strong>Status:</strong> <span style='color: #008000;'>HIGH SUCCESS</span> | <strong>Backups Successful:</strong> ${success_rate}% | <strong>Total Failures:</strong> ${error_count} | <strong>Total Storage:</strong> ${total_storage} GB</p>"
echo "</div>"

echo "<table><tr><td style='width: 50%; text-align: center;'><img src='${DONUT_CHART_URL}' style='max-width: 100%;'></td>"
echo "<td style='width: 50%; text-align: center;'><img src='${STACKED_CHART_URL}' style='max-width: 100%;'></td></tr></table>"

echo "<h2>Top 5 Largest Backups</h2><table><tr><th>Server</th><th>Database Engine</th><th>Size</th></tr>"
echo "${top_backups}" | tail -n +2 | while IFS=$'\t' read -r server engine size; do
    echo "<tr><td>${server}</td><td>${engine}</td><td>${size}</td></tr>"
done
echo "</table>"

echo "<div style='text-align: center; margin-top: 30px; color: #4B286D;'>Report generated by Database Engineering</div>"
echo "</div></body></html>"
} > "${emailFile}"

# === SEND EMAIL ===
{
echo "To: yvette.halili@telusinternational.com"
echo "From: no-reply@telusinternational.com"
echo "MIME-Version: 1.0"
echo "Content-Type: text/html; charset=utf-8"
echo "Subject: Daily Backup Report - ${REPORT_DATE}"
echo ""
cat "${emailFile}"
} | /usr/sbin/sendmail -t

echo "Email sent to yvette.halili@telusinternational.com"
